export const SAVE_PERFORMANCE_ID = 'SAVE_PERFORMANCE_ID';
export const LOAD_SPEECHES = 'LOAD_SPEECHES';
export const SAVE_CURRENT_SPEECH_ID = 'SAVE_CURRENT_SPEECH_ID';
export const CHANGE_STREAMING_STATUS = 'CHANGE_ISPLAYING_STATUS';
export const CHANGE_STREAM_STATE_TO_INITIAL = 'CHANGE_STREAM_STATE_TO_INITIAL';